FROM brayand/fullstack-project-template-composer:1.0.0 AS composer

COPY . /app

WORKDIR /app

RUN composer install

FROM brayand/fullstack-project-template-backend:1.0.0

COPY --from=composer /app /app

COPY docker/php8/docker-start.sh /docker-start.sh

RUN chmod +x /docker-start.sh

RUN mkdir -p /etc/supervisor/conf.d/

COPY docker/php8/laravel-worker.conf /etc/supervisor/conf.d/laravel-worker.conf

WORKDIR /app
